// Pack Library Application
class PackLibrary {
  constructor() {
    this.packs = [];
    this.filteredPacks = [];
    this.currentFilter = {
      search: '',
      category: '',
      sort: 'name'
    };
    this.init();
  }

  async init() {
    this.setupEventListeners();
    this.loadTheme();
    await this.loadPacks();
    this.render();
  }

  setupEventListeners() {
    // Search
    const searchInput = document.getElementById('search-input');
    const searchClear = document.getElementById('search-clear');
    searchInput.addEventListener('input', (e) => this.handleSearch(e));
    searchClear.addEventListener('click', () => this.clearSearch());

    // Filters
    document.getElementById('category-filter').addEventListener('change', (e) => this.handleCategoryFilter(e));
    document.getElementById('sort-filter').addEventListener('change', (e) => this.handleSort(e));

    // Theme
    document.getElementById('theme-toggle').addEventListener('click', () => this.toggleTheme());

    // Settings
    document.getElementById('settings-toggle').addEventListener('click', () => this.openSettings());
    document.querySelector('.modal-close').addEventListener('click', () => this.closeSettings());
    document.getElementById('settings-modal').addEventListener('click', (e) => {
      if (e.target.id === 'settings-modal') this.closeSettings();
    });

    // Settings toggles
    document.getElementById('dark-mode-toggle').addEventListener('change', (e) => {
      this.setDarkMode(e.target.checked);
    });

    document.getElementById('compact-view-toggle').addEventListener('change', (e) => {
      this.setCompactView(e.target.checked);
    });
  }

  async loadPacks() {
    try {
      // Simulate loading packs from the packs folder
      // In a real scenario, this would fetch an index file or scan the directory
      this.packs = await this.scanPacksDirectory();
      this.filteredPacks = [...this.packs];
      return this.packs;
    } catch (error) {
      console.error('Error loading packs:', error);
      this.packs = this.getDefaultPacks();
      this.filteredPacks = [...this.packs];
    }
  }

  async scanPacksDirectory() {
    // This would ideally be generated by a build script
    // For now, return empty and let getDefaultPacks handle it
    return [];
  }

  getDefaultPacks() {
    // Sample packs structure - replace with real data
    return [
      {
        id: 1,
        name: 'Modern UI Kit',
        category: 'designs',
        description: 'A modern and clean UI component library perfect for web applications.',
        thumbnail: '🎨',
        tags: ['ui', 'web', 'components'],
        version: '1.0.0',
        downloads: 234,
        size: '12.5 MB',
        downloadUrl: '#',
        previewUrl: '#'
      },
      {
        id: 2,
        name: 'Dark Theme Template',
        category: 'templates',
        description: 'Professional dark theme template with ready-to-use components.',
        thumbnail: '🌙',
        tags: ['dark', 'theme', 'template'],
        version: '2.1.0',
        downloads: 567,
        size: '8.3 MB',
        downloadUrl: '#',
        previewUrl: '#'
      },
      {
        id: 3,
        name: 'Icon Pack Pro',
        category: 'resources',
        description: 'Comprehensive icon collection with 500+ high-quality icons.',
        thumbnail: '✨',
        tags: ['icons', 'graphics', 'resources'],
        version: '3.2.1',
        downloads: 892,
        size: '15.7 MB',
        downloadUrl: '#',
        previewUrl: '#'
      },
      {
        id: 4,
        name: 'Typography System',
        category: 'designs',
        description: 'Complete typography system with font pairings and sizing scales.',
        thumbnail: '📝',
        tags: ['typography', 'fonts', 'design'],
        version: '1.5.0',
        downloads: 123,
        size: '4.2 MB',
        downloadUrl: '#',
        previewUrl: '#'
      },
      {
        id: 5,
        name: 'Color Palettes',
        category: 'resources',
        description: 'Curated collection of color palettes for various design needs.',
        thumbnail: '🎭',
        tags: ['colors', 'palettes', 'design'],
        version: '2.0.0',
        downloads: 445,
        size: '1.8 MB',
        downloadUrl: '#',
        previewUrl: '#'
      },
      {
        id: 6,
        name: 'Landing Page Template',
        category: 'templates',
        description: 'Responsive landing page template with conversion-optimized design.',
        thumbnail: '🚀',
        tags: ['landing', 'web', 'template'],
        version: '1.2.3',
        downloads: 678,
        size: '9.1 MB',
        downloadUrl: '#',
        previewUrl: '#'
      }
    ];
  }

  handleSearch(e) {
    this.currentFilter.search = e.target.value.toLowerCase();
    this.updateSearchClearButton();
    this.applyFilters();
  }

  clearSearch() {
    document.getElementById('search-input').value = '';
    this.currentFilter.search = '';
    this.updateSearchClearButton();
    this.applyFilters();
  }

  updateSearchClearButton() {
    const clearBtn = document.getElementById('search-clear');
    if (this.currentFilter.search) {
      clearBtn.style.display = 'flex';
    } else {
      clearBtn.style.display = 'none';
    }
  }

  handleCategoryFilter(e) {
    this.currentFilter.category = e.target.value;
    this.applyFilters();
  }

  handleSort(e) {
    this.currentFilter.sort = e.target.value;
    this.applyFilters();
  }

  applyFilters() {
    let filtered = [...this.packs];

    // Search filter
    if (this.currentFilter.search) {
      filtered = filtered.filter(pack => {
        const search = this.currentFilter.search;
        return (
          pack.name.toLowerCase().includes(search) ||
          pack.description.toLowerCase().includes(search) ||
          pack.tags.some(tag => tag.toLowerCase().includes(search))
        );
      });
    }

    // Category filter
    if (this.currentFilter.category) {
      filtered = filtered.filter(pack => pack.category === this.currentFilter.category);
    }

    // Sort
    switch (this.currentFilter.sort) {
      case 'recent':
        filtered.sort((a, b) => b.id - a.id);
        break;
      case 'popular':
        filtered.sort((a, b) => b.downloads - a.downloads);
        break;
      case 'name':
      default:
        filtered.sort((a, b) => a.name.localeCompare(b.name));
    }

    this.filteredPacks = filtered;
    this.render();
  }

  render() {
    const grid = document.getElementById('packs-grid');
    const emptyState = document.getElementById('empty-state');
    const resultsText = document.getElementById('results-text');

    if (this.filteredPacks.length === 0) {
      grid.innerHTML = '';
      emptyState.style.display = 'block';
      resultsText.textContent = this.packs.length === 0
        ? 'No packs available. Add some to the packs folder.'
        : 'No packs match your search criteria.';
      return;
    }

    emptyState.style.display = 'none';
    const count = this.filteredPacks.length;
    resultsText.textContent = `Showing ${count} pack${count !== 1 ? 's' : ''}`;

    grid.innerHTML = this.filteredPacks.map(pack => this.createPackCard(pack)).join('');
  }

  createPackCard(pack) {
    return `
      <div class="pack-card" data-pack-id="${pack.id}">
        <div class="pack-thumbnail">${pack.thumbnail}</div>
        <div class="pack-content">
          <span class="pack-category">${pack.category}</span>
          <h3 class="pack-name">${this.escapeHtml(pack.name)}</h3>
          <p class="pack-description">${this.escapeHtml(pack.description)}</p>

          <div class="pack-meta">
            <div class="pack-meta-item">
              <i class="fas fa-download"></i>
              <span>${pack.downloads}</span>
            </div>
            <div class="pack-meta-item">
              <i class="fas fa-database"></i>
              <span>${pack.size}</span>
            </div>
            <div class="pack-meta-item">
              <i class="fas fa-tag"></i>
              <span>v${pack.version}</span>
            </div>
          </div>

          <div class="pack-tags">
            ${pack.tags.map(tag => `<span class="pack-tag">${this.escapeHtml(tag)}</span>`).join('')}
          </div>

          <div class="pack-actions">
            <a href="${pack.previewUrl}" class="pack-action-btn" target="_blank" rel="noopener">
              <i class="fas fa-eye"></i> Preview
            </a>
            <a href="${pack.downloadUrl}" class="pack-action-btn" target="_blank" rel="noopener">
              <i class="fas fa-download"></i> Download
            </a>
          </div>
        </div>
      </div>
    `;
  }

  escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  toggleTheme() {
    const isDark = document.body.classList.contains('light-mode');
    if (isDark) {
      this.setDarkMode(true);
    } else {
      this.setDarkMode(false);
    }
  }

  setDarkMode(isDark) {
    const darkModeToggle = document.getElementById('dark-mode-toggle');
    if (isDark) {
      document.body.classList.remove('light-mode');
      darkModeToggle.checked = false;
      localStorage.setItem('darkMode', 'true');
    } else {
      document.body.classList.add('light-mode');
      darkModeToggle.checked = true;
      localStorage.setItem('darkMode', 'false');
    }
  }

  setCompactView(isCompact) {
    if (isCompact) {
      document.body.classList.add('compact-view');
      localStorage.setItem('compactView', 'true');
    } else {
      document.body.classList.remove('compact-view');
      localStorage.setItem('compactView', 'false');
    }
  }

  loadTheme() {
    const darkMode = localStorage.getItem('darkMode');
    const compactView = localStorage.getItem('compactView');

    if (darkMode === 'false') {
      this.setDarkMode(false);
    }

    if (compactView === 'true') {
      this.setCompactView(true);
    }
  }

  openSettings() {
    const modal = document.getElementById('settings-modal');
    modal.classList.remove('hidden');
    document.getElementById('dark-mode-toggle').checked = document.body.classList.contains('light-mode');
    document.getElementById('compact-view-toggle').checked = document.body.classList.contains('compact-view');
  }

  closeSettings() {
    document.getElementById('settings-modal').classList.add('hidden');
  }
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', () => {
  window.packLibrary = new PackLibrary();
});

// Keyboard shortcuts
document.addEventListener('keydown', (e) => {
  if (e.key === '?') {
    console.log('Help not implemented yet');
  }
});
